[account]


[[apps]]
name = "Calculator"
slug = "calculator"
path = "./"
command = "python calculator.py"


[[apps]]
name = "Easing"
slug = "easing"
path = "./"
command = "textual easing"


[[apps]]
name = "Keys"
slug = "keys"
path = "./"
command = "textual keys"


[[apps]]
name = "Borders"
slug = "borders"
path = "./"
command = "textual borders"


[[apps]]
name = "Demo"
slug = "demo"
path = "./"
command = "python -m textual"

#[[apps]]
#name = "Terminal"
#slug = "term"
#path = "./"
#terminal = true
